[features]
seeds = false
[programs.localnet]
snug_squad = "5ALT7PNwdVzuMLAMCPvK84s4ZbR8qefihfNC92jV12Pg"

[programs.devnet]
snug_squad = "5ALT7PNwdVzuMLAMCPvK84s4ZbR8qefihfNC92jV12Pg"

[programs.mainnet]
snug_squad = "5ALT7PNwdVzuMLAMCPvK84s4ZbR8qefihfNC92jV12Pg"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
